{% set name = "apache-airflow-providers-edge3" %}
{% set version = "1.1.3" %}
{% set python_min = "3.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/apache_airflow_providers_edge3-{{ version }}.tar.gz
  sha256: 11a9273e33091fa93fbbe82e953d370d55ebe76f73eafe3a8789f43533918be6

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - flit-core ==3.12.0
    - pip
  run:
    - python >={{ python_min }}
    - apache-airflow >=2.10.0
    - pydantic >=2.11.0
    - retryhttp >=1.2.0,!=1.3.0

test:
  imports:
    - airflow.providers.edge3
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://github.com/apache/airflow/
  summary: Provider package apache-airflow-providers-edge3 for Apache Airflow
  license: Apache-2.0
  license_file: src/airflow/providers/edge3/LICENSE
  license_family: Apache
  doc_url: https://airflow.apache.org/docs/apache-airflow-providers-edge3/stable/index.html
  dev_url: https://github.com/apache/airflow/

extra:
  recipe-maintainers:
    - xylar
